### PR TITLE
Add quantize feature to F77 and F90 APIs, with tests and documentation

### PR DESCRIPTION
**Pull request by edwardhartnett**
This won't work until the quantize PR in netcdf-c is merged (https://github.com/Unidata/netcdf-c/pull/2088).

Add the quantize feature to the Fortran APIs.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
OK, apparently no CI for netcdf-fortran yet. ;-)

I added one based on branch ejh_quantize_2 of my fork of netcdf-c. Once those changes are merged this CI can be changed to use master branch of the official netcdf-c repo, or discarded in favor of better CI...

**Comment by WardF** [comment]
Looks great, thanks @edwardhartnett!

**Comment by WardF** [comment]
Ok, I spoke a little soon, although I'm not going to revert the PR because that could end up making more of a mess.  However, trying to link against netCDF 4.8.1 gives the following: 

```
Undefined symbols for architecture arm64:
  "_nc_def_var_quantize", referenced from:
      _nf_def_var_quantize_ in nf_nc4.f90.o
  "_nc_inq_var_quantize", referenced from:
      _nf_inq_var_quantize_ in nf_nc4.f90.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
```

So we will need to query for these functions at configure time and fencepost the code as appropriate.

**Comment by edwardhartnett** [comment]
Problem is that many of the fortran codes don't actually have pre-processing. :-(

So perhaps undoing the merge is a good idea...

**Comment by WardF** [comment]
I'll take a look, thanks for weighing in.  Reverting it out of the blue would possibly require jumping through hoops to re-apply it down the road.  I'm going to revert it, get the testing in (I've got something working now, turns out the main issue was tabs in the yaml file XD), and see what we can do.  Thanks!

**Pull request merged**
