### PR TITLE
delete unuseful code

### PR DESCRIPTION
**Pull request by DragonPara**
After calling the C interface, it will be given the value again

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]

**Review by edwardhartnett — CHANGES_REQUESTED** [review]
What happened to this PR? Suddenly many many files appeared, and they include many files that are generated as part of the build (like Makefile,in files) and should never be committed to the repo.

Was there an accidental commit of files here?

I seem to remember that this PR contained some very simple removal of unneeded code in a few fortran files...

**Comment by DragonPara** [comment]
The GitHub log show the pull has conflicts that must be resolved, so I merged the newest branch.

**Comment by edwardhartnett** [comment]
OK you should undo that merge if you can...

**Comment by DragonPara** [comment]
> OK you should undo that merge if you can...

OK, I've restored it

**Comment by edwardhartnett** [comment]
No, this PR is still messed up and should not be merged...

**Comment by WardF** [comment]
Agreed; it looks lilke the release was merged in, which contains a number of files and changes which are excluded from the development branches by design; hence the `wellspring` model of release, which creates a common root for changes that *can* be merged back upstream, but also allows for a clear branch for the release.  It may be easier to close this and re-open using a current copy of the `main` branch.

**Pull request closed without merging**
