### PR TITLE
nf-config lacked the -I flag when built with CMake

### PR DESCRIPTION
**Pull request by dsakurai**
This bug fix puts the missing "-I" flag in the output of the nf-config utility.

The file `nf-config.cmake.in` expected a MOD_FLAG variable to be set, but I couldn't find it done anywhere reachable from the CMakeLists.txt.
So I simply added such a line.

Could you have a review and merge if appropriate?

### CODE REVIEW

**Comment by WardF** [comment]
Thanks! Can you sign the license/cla so that I can accept the pull request? Or, if that is an issue, let me know and I'll do this in a different PR request. Thank you very much for the fix!

**Comment by dsakurai** [comment]
I did sign the cla but apparently it's not taking effect. Could you do it in a PR request, perhaps?

**Comment by WardF** [comment]
I will do so, thanks!

**Comment by WardF** [comment]
Merging in #243

**Pull request closed without merging**
