### PR TITLE
Next round of clean up of build system, also fixed some warnings and added some docs

### LINKED ISSUE #140: warnings in fortran build for nc_inq_varnparams
Lots of warnings in the fortran build. Here's one:

```
gfortran  -g -Wall -c -o module_netcdf4_nc_interfaces.o  module_netcdf4_nc_interfaces.f90
module_netcdf4_nc_interfaces.f90:743:1:

  Function nc_inq_varnparams(ncid, varid, nparams) BIND(C)
 1
Warning: Implicitly declared BIND(C) variable ‘nc_inq_varnparams’ at (1) may not be C interoperable [-Wc-binding-type]
module_netcdf4_nc_interfaces.f90:743:1:

  Function nc_inq_varnparams(ncid, varid, nparams) BIND(C)
 1
Warning: Implicitly declared BIND(C) function ‘nc_inq_varnparams’ at (1) may not be C interoperable [-Wc-binding-type]
```

I will see what can be done here...

### LINKED ISSUE #141: move handling of F77 man page to docs directory, add doxygen build
The man page source (netcdf.m4) is in docs, but it is being turned into the F77 man page in libsrc, which is where the old cfortran.h based F77 API was, but is no longer.

So I will move handling of the F77 man page into the doc directory.

Also, even with --enable-doxygen the documentation does not build with make all. Doxygen is found but not used. I have put the stuff needed in docs/Makefile.am to build the documentation when --enable-doxygen is used with configure.

### LINKED ISSUE #142: clean target removed needed fills.nc file, causing build to subsequently break on nf_test/ftest
It's failing like this:

```
ed@mikado:~/tmp/nf1/nf_test$ ./ftest
 
 *** Testing netCDF-2 Fortran 77 API.
 *** testing nccre ...
 *** testing ncddef ...
 *** testing ncvdef ...
 *** testing ncapt, ncaptc ...
 *** testing ncclos ...
 *** testing ncvpt1 ...
 *** testing ncvgt1 ...
 *** testing ncvpt ...
 *** testing ncopn, ncinq, ncdinq, ncvinq, ncanam, ncainq ...
 *** testing ncvgt, ncvgtc ...
 *** testing ncagt, ncagtc ...
 *** testing ncredf, ncdren, ncvren, ncaren, ncendf ...
 *** testing ncacpy ...
 *** testing ncadel ...
 *** testing fill values ...
ncopen: filename "fills.nc": No such file or directory
NCOPN: : Unknown Error
ncvarid: ncid -1: NetCDF: Not a valid ID
ncvarid: ncid -1: NetCDF: Not a valid ID
ncvarid: ncid -1: NetCDF: Not a valid ID
ncvarid: ncid -1: NetCDF: Not a valid ID
ncvarid: ncid -1: NetCDF: Not a valid ID
NCVGT1: : NetCDF: Not a valid ID
NCVGT1: : NetCDF: Not a valid ID
NCVGT1: : NetCDF: Not a valid ID
NCVGT1: : NetCDF: Not a valid ID
NCVGT1: : NetCDF: Not a valid ID
 error in byte fill value
 error in double fill value
 error in float fill value
 error in long fill value
 error in short fill value
 Total number of failures:           11
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
STOP 2
```

Not sure why this was not caught by my CI system...

### LINKED ISSUE #144: nfconfig.inc should not be installed, but is
We have nfconfig.inc, which is the fortran equivalent of config.h.

Like config.h it should not be installed, it is used only during the build.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #144.
Fixes #142 
Fixes #141 
Fixes #140 

Fix some warnings, add some documentation, clean up build system a little more.

### CODE REVIEW

**Comment by WardF** [comment]
These are taking me a bit longer to review due to my relative unfamiliarity with Fortran compared to C.  With the C release recently out, I'm going to try to get a fortran release out relatively soon.  Thanks for the PR's, reviewing down the line and merging in. 

Do you have access to the Intel Fortran compilers, @edhartnett ?

**Comment by edhartnett** [comment]
Howdy @WardF! Yes I have access to intel compilers. In fact, at @DennisHeimbigner suggestion I downloaded the free version and have it on my development/CI machine. So I will set up some CI jobs that use it to make sure it doesn't get broken. ;-)

Probably want to hold the release at least a week or two until we get the issues I just found resolved.

The Fortran build has become very complicated over the years with a lot of repeated code, etc. I think it will be a lot easier to understand in a few weeks, when the current PRs and also a few more I have coming will make things more simple, robust, and correct.

**Comment by WardF** [comment]
Interesting, last I had checked, Intel was not providing a free community edition. I will have to check that out myself. Thanks! The release will be at least a couple of weeks so no worries there.  Not rushing to get that one out the door.

**Comment by DennisHeimbigner** [comment]
I do not recall finding a free Intel, but I did find a free PGI compiler.

**Comment by edhartnett** [comment]
Well I guess I was thinking of something else.

I do have access to an ifort build on HPC and I just ran the end-point of my current series of PRs, and it worked fine. ;-)

Do you guys have an ifort? It would be good if you could buy one, it is very popular in the HPC world.

**Pull request merged**
