### PR TITLE
CI improvements: don't try to cache netcdf-c main build, add parallel I/O testing, and add testing with HDF5-1.12.2

### LINKED ISSUE #349: GitHub actions for main branch of netcdf-c does not work because it is cached...
In the GitHub actions workflow, we test with netcdf-c 4.7.4, 4.8.1, and main.

But the built dependencies are cached, which means they are not built every time. So the main that we are testing with is the cached main, not the current main.

Instead, we should add a workflow that builds with netcdf-c main, and does not cache it. Then we can take main out of the list of versions built by the existing workflow. So the existing workflow can build with released versions, and we can have a separate workflow that builds with the current netcdf-c main.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #349 
Fixes #343

Add parallel I/O build and test for netcdf-fortran with autotools and add hdf5-1.12.1 testing.

Also change the CI so that netcdf-c is not cached when building main, but is when building other branches.

The intent is that when netcdf-fortran is tested against netcdf-c main branch, the netcdf-c main branch is fetched and built each time, and never cached.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
OK, this is a much cleaner way than my former PR #346 

Now I will try and add parallel I/O...

**Comment by edwardhartnett** [comment]
OK, now adding HDF5-1.12.1...

**Comment by edwardhartnett** [comment]
@WardF once this is merged I'll resubmit some other PRs.

This gets netcdf-fortran testing in a better place for the upcoming release...

**Comment by edwardhartnett** [comment]
OK, I'm changing to the just-released HDF5 1.12.2. Let's see how it does...

**Comment by edwardhartnett** [comment]
Looks like HDF5 1.12.2 works out of the box. That's nice!

**Comment by edwardhartnett** [comment]
I will close this but it does demonstrate that @WardF can update the CI to hdf5-1.12.2 at any time.

**Comment by edwardhartnett** [comment]
Actually I will reopen this because it adds parallel I/O builds to the CI.

**Comment by WardF** [comment]
Out of curiosity (now that I'm turning to this (and answering emails, I'll follow up with you shortly)), why did you close this? Was there an issue, or was it to lower the overhead of a new release? Part of the next release cycle will be expanding our CI for netCDF-Fortran, so if it's the latter, feel free to reopen and I'll merge in. Thanks!

**Comment by edwardhartnett** [comment]
There were conflicts so I was planning on doing a fresh PR with the parallel I/O testing in CI. I'll take a stab at that tomorrow...

**Comment by edwardhartnett** [comment]
Fixed conflicts and am reopening this PR.

**Comment by edwardhartnett** [comment]
@WardF I have updated this PR to retain your addition of netcdf-c-4.9.0, add hdf5-1.12.2, and upgraded hdf5-1.10.8 to hdf5-1.10.9.

**Comment by edwardhartnett** [comment]
I have taken out hdf5-1.10.9 and left hdf5-1.12.2.

I don't think it's all that important to test netcdf-fortran with different hdf5 versions, since we already do that with netcdf-c, which has much more extensive testing.

**Comment by edwardhartnett** [comment]
@WardF it would be good to get this merged, so that we prevent breakage during the rest of the preparations for the next release.

**Review by WardF — APPROVED** [review]

**Pull request merged**
