### PR TITLE
Fix for nf-config using autotools

### PR DESCRIPTION
**Pull request by mathomp4**
This PR is to restore the previous functionality of `nf-config` as detailed in https://github.com/Unidata/netcdf-fortran/issues/270.

Currently, building netcdf-fortran with autotools results in `nf-config` that returns:
```
-L/Users/mathomp4/NetcdfFortranFix/before/lib 
-lnetcdff
```
where you only get out the `libnetcdff` link, but not everything you need to link to netcdf-fortran.

Before https://github.com/Unidata/netcdf-fortran/commit/82273f82f5f20ed5e2e64d847476dfc48b8f33ff, `nf-config --flibs` returned something like:
```
-L/Users/mathomp4/NetcdfFortranFix/after/lib 
-lnetcdff -lnetcdf -lm 
-L/Users/mathomp4/NetcdfFortranFix/after/lib 
-L/Users/mathomp4/NetcdfFortranFix/after/lib 
-lnetcdf -ljpeg -lmfhdf -ldf -ljpeg -lhdf5_hl -lhdf5 -lm -lz 
-L/Users/mathomp4/NetcdfFortranFix/after/lib 
-lsz -ljpeg -ldl -lm
```
(which is what I get with this PR). This is essentially what you get from `nc-config --libs` appended to what's needed from netcdf-fortran

### CODE REVIEW

**Comment by WardF** [comment]
Thanks! Taking a look at the Travis-CI failure.

**Comment by WardF** [comment]
Ok, I need to tweak the travis config.

**Comment by mathomp4** [comment]
> Ok, I need to tweak the travis config.

Dang. Part of me was hoping I somehow managed to break the entire code by removing a single character! 😄

**Comment by WardF** [comment]
> > Ok, I need to tweak the travis config.
> 
> Dang. Part of me was hoping I somehow managed to break the entire code by removing a single character! 😄

I mean, have you seen 'Garfield without Garfield'? Sometimes removing a single character can have a profound impact ;).

**Comment by WardF** [comment]
Can you pull the latest master into your branch? That should resolve this. If not, I can pull your PR into a local branch and get the update travis config merged in that way.

**Comment by mathomp4** [comment]
> Can you pull the latest master into your branch? That should resolve this. If not, I can pull your PR into a local branch and get the update travis config merged in that way.

Okay. Just did:
```
  git remote add upstream https://github.com/Unidata/netcdf-fortran.git
  git remote update
  git merge upstream/master
  git push
```
which I think is right?

**Comment by WardF** [comment]
Yup! Thanks again!

**Pull request merged**
