### PR TITLE
got doxygen build working

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #75.

Minor changes to get doxygen build working with existing .md files.

This produces pretty decent documentation. @WardF I suggest you build it and put it up on the website while I work on the rest of the docs. It's very important for HPC users to have fortan docs. They do not use the C library - they use fortran.

### CODE REVIEW

**Comment by WardF** [comment]
3,646 files changed?

**Comment by edhartnett** [comment]
Stand by I will take a look...

**Comment by zerothi** [comment]
May I suggest to put the documentation in a separate branch? There is no need for the source code to ship all documentation files (very large source files).

**Comment by WardF** [comment]
@zerothi My assumption is that the generated files were added accidentally; typically we won’t store generated files under version control because the means to generate them on demand are available.

**Comment by zerothi** [comment]
Ok, sorry for the blurp then ;)

**Comment by WardF** [comment]
No problem :)

**Comment by edhartnett** [comment]
Yes my fault. I inadvertently checked in all the generated files. Of course that should not be done! ;-)

I have reverted that and now there is just one file changed.

Turns out there is a way to get github to show the generated documentation. It's described here:
https://pages.github.com/

I did this for netcdf-fortran. The output can be seen here:
https://hpc-netcdf.github.io/

**Pull request merged**
