### PR TITLE
Fix 2 broken parallel tests, clean out some remaining support for legacy cfortran build and upper-case mod file names

### LINKED ISSUE #160: F90 uppercase mod code no longer used or necessary
There was one fortran compiler, I can't remember which one, which changed the names of the mod files to all upper-case. How annoying! That required a bunch of code in the Makefile.am and some in configure.ac.

However, ever since the Fortran 2003 compile changes were put in place, this upper-case code has never been run. And no one has missed it. This matches my experience on a number of other Fortran packages, none of which have to deal with uppercased mod file names. So whatever compiler used to commit this stupidity is apparently long gone.

So I will remove the upper-casing stuff from the autotools build system (it was never handled in the CMake build system, so nothing to do there.)

### LINKED ISSUE #161: Remove unworking and unused --enable-dll option
A long, long time ago, long before Ward came along and wrote the cmake build, I tried to get Windows DLLs out of mingw. I had some limited success, but in general, the whole thing was too fragile and I don't think anyone used it. It requires that the user install the mingw environment on their Windows machine, and this is a pretty high barrier for Visual Studio programmers.

Since then, we have the cmake builds, which are the approved way to build netCDF for windows. They build with visual studio and don't require that the Windows user know or use mingw.

I took all the mingw stuff out of the C library, but there is still some to be removed in the fortran library.

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #157.
Fixes #161.
Fixes #160.
Part of #85.

In this PR I fix two of the three broken parallel tests.

Also continuing to clean up residue of the ancient cfortran.h build, especially in the acinclude.m4 file, which contains a lot of macros we no longer use anywhere, since we no longer do the cfortran build.

Also removed handling for upper-case mod file names. This has been turned off in the build anyway, and the fortran compiler that subjected me to this horror has died and presumably gone to compiler hell. Which just goes to show, the best revenge really is living well.

Also updated release notes, and added link to documentation in the readme.

### CODE REVIEW

**Comment by edhartnett** [comment]
Also @WardF I have upgraded my CI system to build netcdf-fortran with and without parallel I/O with netcdf-c 4.6.3 and hdf5-1.10.5.

**Comment by edhartnett** [comment]
My CI system is showing problems with parallel builds and 4.6.1. I will take a look and fix...

**Comment by edhartnett** [comment]
OK, this branch is now all green on my CI system and on travis, and is ready to merge.

**Comment by WardF** [comment]
Awesome, thanks!

**Pull request merged**
