### PR TITLE
Fixed f90tst_parallel3.F90 parallel test

### LINKED ISSUE #155: most or all parallel I/O tests not really running
In nf_test/f90tst_parallel.f90 and f90tst_parallel2.f90 we have code that looks like this:

```
#ifdef NF_HAS_PNETCDF
  mode_flag = IOR(nf90_clobber, nf90_mpiio)
  call parallel_io(mode_flag)
#endif

#ifdef NF_HAS_PARALLEL4
  mode_flag = IOR(nf90_netcdf4, nf90_classic_model)
  mode_flag = IOR(mode_flag, nf90_mpiposix)
  mode_flag = IOR(mode_flag, nf90_clobber)
  call parallel_io(mode_flag)
#endif
```

The code in these ifdef blocks will never run, because we produce a config.h (and an nfconfig.inc) by using AC_CONFIG_HEADERS() in the configure.ac. This causes defines to end up in the configure file (typically config.h but in this case also nfconfig.inc) instead of as -D defines on the compile command line. But this include file is not included by the test.

This can be seen from the compile of the test:

```
ed@mikado:~/tmp/netcdf-fortran/nf_test$ make f90tst_parallel2
mpifort -DHAVE_CONFIG_H -I. -I.. -I../libsrc  -I../fortran -I../fortran -I/usr/local/netcdf-c-4.6.2_mpich-3.2/include -I../fortran  -g -Wall -c -o f90tst_parallel2.o f90tst_parallel2.F90
f90tst_parallel2.F90:47:22:

   integer :: mode_flag
                      1
Warning: Unused variable ‘mode_flag’ declared at (1) [-Wunused-variable]
f90tst_parallel2.F90:95:0:

   subroutine parallel_io(mode_flag)
 
Warning: ‘parallel_io’ defined but not used [-Wunused-function]
/bin/bash ../libtool  --tag=FC   --mode=link mpifort -I../fortran  -g -Wall  -L/usr/local/netcdf-c-4.6.2_mpich-3.2/lib -o f90tst_parallel2 f90tst_parallel2.o ../fortran/libnetcdff.la -lnetcdf -ldl -lz -lcurl -lm 
libtool: link: mpifort -I../fortran -g -Wall -o .libs/f90tst_parallel2 f90tst_parallel2.o  -L/usr/local/netcdf-c-4.6.2_mpich-3.2/lib ../fortran/.libs/libnetcdff.so /usr/local/netcdf-c-4.6.2_mpich-3.2/lib/libnetcdf.so -ldl -lz /usr/lib/x86_64-linux-gnu/libcurl-nss.so -lm -pthread -Wl,-rpath -Wl,/home/ed/test_fortran/lib -Wl,-rpath -Wl,/usr/local/netcdf-c-4.6.2_mpich-3.2/lib
```

(Note the warning, which lead me to this problem. Since the ifdefs don't get defined, the parallel_io() test function is never being run.)

I will fix the problem of the defines not being correctly handled and make sure this test actually passes. Unfortunately just putting in an include of nfconfig.inc causes all kinds of compile errors. I will circle around to this again after dealing with all the easy warnings. ;-)

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #157.
Fixes #155

In this PR I remove the nfconfig file and all its related trappings.

In netcdf-fortran, I started with a configure.in file (written by Steve) and added automake (and changed the name, as was recommended, to configure.ac).

So some of what is present is simply an artifact of those times, and the nfconfig.inc is part of that. Because the netCDF-c build used config.h, we had an equivalent for fortran.

But since then I have learned a lot more about autotools and fortran and done several more fortran packages. Fortran does better without a config file, since there is no standard for fortran pre-processing. Instead, defining macros with the -D option to compilers works best.

So that is what is implemented here. This causes the parallel tests to run again, and I had to comment a couple of them out because they fail. I will hit that in my next PR. ;-)

In this PR I also fix one of the two currently broken parallel tests.

### CODE REVIEW

**Comment by WardF** [comment]
Thanks for the PR; the tests had failed so I've restarted them and will follow back up if they fail again.

**Comment by WardF** [comment]
Seeing a number of fortran related failures, will see if I observe them outside the docker environment.

**Comment by WardF** [comment]
Failures can be observed here:

* http://cdash.unidata.ucar.edu/viewTest.php?onlyfailed&buildid=7390

**Comment by edhartnett** [comment]
Ok stand by.

**Comment by edhartnett** [comment]
I'll fall back to the previous PR and circle around to this one again when it is merged. Thanks! Ed

**Pull request closed without merging**
