### PR TITLE
correctly detect absence of szip write capability

### LINKED ISSUE #219: build fails to detect absence of szip in netcdf-c
On current master, if built against a netcdf-c that does not have szip, then netcdf-fortran will incorrectly run some szip tests which will fail.

This is due to a bug in the configure script. I will have a PR up shortly with a fix.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #219

### CODE REVIEW

**Comment by WardF** [comment]
Still seeing a failure when trying to build/link netcdf-fortran on our systems when netcdf-c was built without szip support. Diagnosing.

**Comment by WardF** [comment]
Clarification: when building via cmake, not configure.

**Comment by edwardhartnett** [comment]
OK, let me take a look...

**Comment by edwardhartnett** [comment]
Actually the master of netcdf-fortran builds fine for me with cmake against a current master of netcdf-c build without szip.

What error do you see?

**Comment by WardF** [comment]
It was environmental; `make install` for libnetcdf wasn't overwriting the extant libnetcdf, so I was working against a version w/out `nc_def_var_szip`.  Removing the previous version manually and reinstalling corrected the issue. Sorry for the false alarm.

**Comment by edwardhartnett** [comment]
It was very useful, because I discovered that my Jenkins-based CI testing was not really getting the correct branch, and also that I did not include this szip test in cmake. So I have fixed the first and am working on the second...

**Pull request merged**
