### PR TITLE
Support 64-bit integer memory type

### PR DESCRIPTION
**Pull request by wkliao**
This PR allows user programs to read/write 64-bit integer data of internal memory type (i.e. integer*8) to/from ~~classic CDF~~ NetCDF files. It was tested using the following NetCDF-C settings.
* --disable-netcdf4 --disable-pnetcdf
* --enable-netcdf4 --disable-pnetcdf
* --disable-netcdf4 --enable-pnetcdf
* --enable-netcdf4 --enable-pnetcdf

### CODE REVIEW

**Comment by edhartnett** [comment]
Wait, does this capability exist in the C library?

**Comment by wkliao** [comment]
In NetCDF-C header file, netcdf.h, such APIs have been defined. For example,
```
EXTERNL int
nc_put_vara_longlong(int ncid, int varid, const size_t *startp,
                  const size_t *countp, const long long *op);
```

**Comment by wkliao** [comment]
I believe this PR also addresses issue #62 
The newly added test program `nf03_test/tst_fill_int64.F90` does the checking.

**Comment by WardF** [comment]
Thank you very much, this is much appreciated!

**Pull request merged**
