### PR TITLE
CMakeLists.txt: check for the C types that match Fortran ones.

### PR DESCRIPTION
**Pull request by multiplemonomials**
When I was integrating netcdf-fortran into Amber-MD's build system, I noticed that the `ENABLE_FORTRAN_TYPE_CHECKS` block in CMakeLists.txt (which seems important for portability) was marked as TODO.  Since my CMake-ized PNetcdf also needed this feature, I wrote it for you guys.  I have tested it on several machines and it seems to work fine.

I also made two other small changes to CMakeLists.txt: I removed the unnecessary full include paths to standard library modules, and I removed QUIET from the `find_package(netCDF)` call.  This makes it so the user gets a lot more information if it can't find netcdf.

Let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by multiplemonomials** [comment]
Hmm, I signed the CLA, but it's still showing as "not signed yet".  Any idea what's going on?

**Comment by WardF** [comment]
No idea, I did not know this had been enabled. I will ask out CLA admin.

**Comment by WardF** [comment]
@dopplershift Any idea what might be happening in this case?

**Comment by multiplemonomials** [comment]
Oh huh, it seems to be fixed now.  I guess there was some sort of time lag?  Anyway, how does this PR look to you guys?

**Comment by dopplershift** [comment]
Some times GitHub's hook delivery can be a bit delayed. It looks like everything is fine now. Let me know if you run into any other problems!

**Comment by multiplemonomials** [comment]
So, what is the status of this PR?  Is it under review?  Are there any changes that you need me to make?

**Comment by WardF** [comment]
I'm currently working on the 4.5.0 release, and answering support questions. I'll take a look at this ASAP, thanks!

**Comment by WardF** [comment]
Being reviewed by our new fortran contributor/dev @piqueen314 for inclusion; getting the next release out in short order is high priority.

**Pull request merged**
