### PR TITLE
Fix parallel I/O test not running, remove nfconfig.inc.

### LINKED ISSUE #155: most or all parallel I/O tests not really running
In nf_test/f90tst_parallel.f90 and f90tst_parallel2.f90 we have code that looks like this:

```
#ifdef NF_HAS_PNETCDF
  mode_flag = IOR(nf90_clobber, nf90_mpiio)
  call parallel_io(mode_flag)
#endif

#ifdef NF_HAS_PARALLEL4
  mode_flag = IOR(nf90_netcdf4, nf90_classic_model)
  mode_flag = IOR(mode_flag, nf90_mpiposix)
  mode_flag = IOR(mode_flag, nf90_clobber)
  call parallel_io(mode_flag)
#endif
```

The code in these ifdef blocks will never run, because we produce a config.h (and an nfconfig.inc) by using AC_CONFIG_HEADERS() in the configure.ac. This causes defines to end up in the configure file (typically config.h but in this case also nfconfig.inc) instead of as -D defines on the compile command line. But this include file is not included by the test.

This can be seen from the compile of the test:

```
ed@mikado:~/tmp/netcdf-fortran/nf_test$ make f90tst_parallel2
mpifort -DHAVE_CONFIG_H -I. -I.. -I../libsrc  -I../fortran -I../fortran -I/usr/local/netcdf-c-4.6.2_mpich-3.2/include -I../fortran  -g -Wall -c -o f90tst_parallel2.o f90tst_parallel2.F90
f90tst_parallel2.F90:47:22:

   integer :: mode_flag
                      1
Warning: Unused variable ‘mode_flag’ declared at (1) [-Wunused-variable]
f90tst_parallel2.F90:95:0:

   subroutine parallel_io(mode_flag)
 
Warning: ‘parallel_io’ defined but not used [-Wunused-function]
/bin/bash ../libtool  --tag=FC   --mode=link mpifort -I../fortran  -g -Wall  -L/usr/local/netcdf-c-4.6.2_mpich-3.2/lib -o f90tst_parallel2 f90tst_parallel2.o ../fortran/libnetcdff.la -lnetcdf -ldl -lz -lcurl -lm 
libtool: link: mpifort -I../fortran -g -Wall -o .libs/f90tst_parallel2 f90tst_parallel2.o  -L/usr/local/netcdf-c-4.6.2_mpich-3.2/lib ../fortran/.libs/libnetcdff.so /usr/local/netcdf-c-4.6.2_mpich-3.2/lib/libnetcdf.so -ldl -lz /usr/lib/x86_64-linux-gnu/libcurl-nss.so -lm -pthread -Wl,-rpath -Wl,/home/ed/test_fortran/lib -Wl,-rpath -Wl,/usr/local/netcdf-c-4.6.2_mpich-3.2/lib
```

(Note the warning, which lead me to this problem. Since the ifdefs don't get defined, the parallel_io() test function is never being run.)

I will fix the problem of the defines not being correctly handled and make sure this test actually passes. Unfortunately just putting in an include of nfconfig.inc causes all kinds of compile errors. I will circle around to this again after dealing with all the easy warnings. ;-)

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #155 

In this PR I remove the nfconfig file and all its related trappings.

In netcdf-fortran, I started with a configure.in file (written by Steve) and added automake (and changed the name, as was recommended, to configure.ac).

So some of what is present is simply an artifact of those times, and the nfconfig.inc is part of that. Because the netCDF-c build used config.h, we had an equivalent for fortran.

But since then I have learned a lot more about autotools and fortran and done several more fortran packages. Fortran does better without a config file, since there is no standard for fortran pre-processing. Instead, defining macros with the -D option to compilers works best.

So that is what is implemented here. This causes the parallel tests to run again, and I had to comment a couple of them out because they fail. I will hit that in my next PR. ;-)

### CODE REVIEW

**Comment by edhartnett** [comment]
Well we are moving along right quickly! :-) Here the next PR in the series.

**Comment by edhartnett** [comment]
This work is included in the next PR, so I will combine them and close this one.

**Comment by edhartnett** [comment]
@WardF if we could get this one merged I'd like to get the rest of the parallel I/O tests working...

**Comment by WardF** [comment]
Merging asap, having some connectivity issues at home. Will be merged as soon as this is resolved.

**Comment by WardF** [comment]
Ah, it is not my connectivity that is the problem: https://www.githubstatus.com/

Regardless, merging as soon as this is resolved.

**Pull request merged**
